# Generated by Django 4.2 on 2025-03-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="brands/", verbose_name="Logo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="Image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Discounted Price",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")],
                        default="new",
                        max_length=10,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("pre_order", "Pre-Order"),
                        ],
                        default="in_stock",
                        max_length=15,
                        verbose_name="Availability",
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Color")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(blank=True, max_length=100, verbose_name="Engine"),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("semi_auto", "Semi-Automatic"),
                        ],
                        max_length=20,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasoline"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                        verbose_name="Fuel type",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For used vehicles",
                        null=True,
                        verbose_name="Mileage",
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Number of seats"
                    ),
                ),
                (
                    "doors",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Number of doors"
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, verbose_name="Additional features"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_details",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Details",
                "verbose_name_plural": "Vehicle Details",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alternative text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine_capacity",
                    models.CharField(
                        help_text="e.g. 150cc, 250cc",
                        max_length=50,
                        verbose_name="Engine capacity",
                    ),
                ),
                (
                    "horsepower",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Horsepower"
                    ),
                ),
                (
                    "fuel_tank_capacity",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Fuel tank capacity"
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transmission"
                    ),
                ),
                (
                    "mileage",
                    models.CharField(
                        blank=True,
                        help_text="For used motorcycles",
                        max_length=50,
                        verbose_name="Mileage",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motorcycle_details",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motorcycle Details",
                "verbose_name_plural": "Motorcycle Details",
            },
        ),
        migrations.CreateModel(
            name="AgriculturalMachinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machinery_type",
                    models.CharField(
                        help_text="e.g. Tractor, Harvester, Planter",
                        max_length=100,
                        verbose_name="Machinery type",
                    ),
                ),
                (
                    "engine_power",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Engine power"
                    ),
                ),
                (
                    "operating_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For used machinery",
                        null=True,
                        verbose_name="Operating hours",
                    ),
                ),
                (
                    "features",
                    models.TextField(blank=True, verbose_name="Additional features"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machinery_details",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agricultural Machinery Details",
                "verbose_name_plural": "Agricultural Machinery Details",
            },
        ),
    ]
