# Generated by Django 4.2 on 2025-03-24 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Pago Inicial",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(verbose_name="Plazo (meses)"),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Cuota Mensual"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Enviada"),
                            ("in_review", "En Revisión"),
                            (
                                "additional_info_required",
                                "Información Adicional Requerida",
                            ),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo de Rechazo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Aprobación"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Rechazo"
                    ),
                ),
                (
                    "financing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="financing.financingplan",
                        verbose_name="Plan de Financiamiento",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Crédito",
                "verbose_name_plural": "Solicitudes de Crédito",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("submitted", "Enviada"),
                            ("in_review", "En Revisión"),
                            (
                                "additional_info_required",
                                "Información Adicional Requerida",
                            ),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cambio"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.creditapplication",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cambiado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Solicitud",
                "verbose_name_plural": "Estados de Solicitudes",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="applications.creditapplication",
                        verbose_name="Solicitud",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Solicitud",
                "verbose_name_plural": "Notas de Solicitudes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Cédula de Identidad"),
                            ("income_proof", "Comprobante de Ingresos"),
                            ("bank_statement", "Estado de Cuenta Bancario"),
                            ("tax_return", "Declaración de Impuestos"),
                            ("utility_bill", "Factura de Servicios"),
                            ("reference_letter", "Carta de Referencia"),
                            ("vehicle_images", "Imágenes del Vehículo"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="application_documents/%Y/%m/", verbose_name="Archivo"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.creditapplication",
                        verbose_name="Solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Solicitud",
                "verbose_name_plural": "Documentos de Solicitud",
            },
        ),
    ]
