# Generated by Django 4.2 on 2025-03-24 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("programmed", "Programmed Purchase"),
                            ("immediate", "Immediate Adjudication"),
                        ],
                        max_length=15,
                        verbose_name="Plan Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "min_term",
                    models.PositiveIntegerField(verbose_name="Minimum Term (months)"),
                ),
                (
                    "max_term",
                    models.PositiveIntegerField(verbose_name="Maximum Term (months)"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Annual Interest Rate (%)",
                    ),
                ),
                (
                    "adjudication_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=45.0,
                        help_text="Percentage of total to reach before adjudication",
                        max_digits=5,
                        verbose_name="Adjudication Percentage",
                    ),
                ),
                (
                    "down_payment_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Required initial payment percentage",
                        max_digits=5,
                        verbose_name="Down Payment Percentage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financing Plan",
                "verbose_name_plural": "Financing Plans",
            },
        ),
        migrations.CreateModel(
            name="FinancingSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_months",
                    models.PositiveIntegerField(verbose_name="Term (months)"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Down Payment"
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monthly Payment"
                    ),
                ),
                (
                    "adjudication_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment at adjudication time for programmed purchase",
                        max_digits=12,
                        null=True,
                        verbose_name="Adjudication Payment",
                    ),
                ),
                (
                    "adjudication_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Adjudication Month"
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Interest"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total Amount to Pay",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="financing.financingplan",
                        verbose_name="Financing Plan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financing Simulation",
                "verbose_name_plural": "Financing Simulations",
            },
        ),
        migrations.CreateModel(
            name="PlanRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Requirement Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Mandatory"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="financing.financingplan",
                        verbose_name="Financing Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Requirement",
                "verbose_name_plural": "Plan Requirements",
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(verbose_name="Payment Number"),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Principal"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Interest"
                    ),
                ),
                (
                    "total_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Payment"
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Remaining Balance",
                    ),
                ),
                (
                    "is_adjudication",
                    models.BooleanField(
                        default=False, verbose_name="Is Adjudication Payment"
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="financing.financingsimulation",
                        verbose_name="Simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Schedule",
                "verbose_name_plural": "Payment Schedules",
                "ordering": ["payment_number"],
            },
        ),
    ]
